site_name: 'プログラミング言語 Mokkosu'
repo_url: https://github.com/lambdataro/Mokkosu
theme: Bootstrap
pages:
- ['index.md', 'トップ']
- ['start/install.md', '始め方', 'インストールと実行']
- ['start/beginner.md', '始め方', 'プログラミング初心者向け']
- ['start/programmer.md', '始め方', 'プログラミング経験者向け']
- ['start/fptomok.md', '始め方', '関数型言語経験者向け']
- ['tutorial/part01.md', 'チュートリアル', '第1章 はじめよう']
- ['tutorial/part02.md', 'チュートリアル', '第2章 基本的な構文と型']
- ['tutorial/part03.md', 'チュートリアル', '第3章 リストとタプル']
- ['reference/basic.md', 'リファレンスマニュアル', '基本事項']
- ['reference/statement.md', 'リファレンスマニュアル', '文']
- ['reference/type.md', 'リファレンスマニュアル', '型とリテラル']
- ['reference/expression.md', 'リファレンスマニュアル', '式']
- ['reference/pattern.md', 'リファレンスマニュアル', 'パターン']
- ['reference/dotnet.md', 'リファレンスマニュアル', '.NET関連の式']
- ['reference/corelib.md', 'リファレンスマニュアル', 'コアライブラリ']
- ['reference/list.md', 'リファレンスマニュアル', 'リストライブラリ']
- ['reference/graphics.md', 'リファレンスマニュアル', 'グラフィックスライブラリ']
- ['sample.md', 'サンプル']
